"""
    GraphSense API

    GraphSense API  # noqa: E501

    The version of the OpenAPI document: 0.5.2-dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import graphsense
from graphsense.model.address_tag import AddressTag
from graphsense.model.entity_tag import EntityTag
globals()['AddressTag'] = AddressTag
globals()['EntityTag'] = EntityTag
from graphsense.model.address_and_entity_tags import AddressAndEntityTags


class TestAddressAndEntityTags(unittest.TestCase):
    """AddressAndEntityTags unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAddressAndEntityTags(self):
        """Test AddressAndEntityTags"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AddressAndEntityTags()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
