"""
    GraphSense API

    GraphSense API  # noqa: E501

    The version of the OpenAPI document: 0.4.5
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import graphsense
from graphsense.model.values import Values
globals()['Values'] = Values
from graphsense.model.block_tx_utxo import BlockTxUtxo


class TestBlockTxUtxo(unittest.TestCase):
    """BlockTxUtxo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBlockTxUtxo(self):
        """Test BlockTxUtxo"""
        # FIXME: construct object with mandatory attributes with example values
        # model = BlockTxUtxo()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
