# coding: utf-8

"""
    GraphSense API

    GraphSense API  # noqa: E501

    The version of the OpenAPI document: 0.4.4
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import graphsense
from graphsense.api.txs_api import TxsApi  # noqa: E501
from graphsense.rest import ApiException


class TestTxsApi(unittest.TestCase):
    """TxsApi unit test stubs"""

    def setUp(self):
        self.api = graphsense.api.txs_api.TxsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_tx(self):
        """Test case for get_tx

        Returns details of a specific transaction identified by its hash.  # noqa: E501
        """
        pass

    def test_list_txs(self):
        """Test case for list_txs

        Returns details of a specific transaction identified by its hash.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
