"""
    GraphSense API

    GraphSense API  # noqa: E501

    The version of the OpenAPI document: 0.4.5
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import graphsense
from graphsense.model.stats_tags_source import StatsTagsSource


class TestStatsTagsSource(unittest.TestCase):
    """StatsTagsSource unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStatsTagsSource(self):
        """Test StatsTagsSource"""
        # FIXME: construct object with mandatory attributes with example values
        # model = StatsTagsSource()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
