"""
    GraphSense API

    GraphSense API  # noqa: E501

    The version of the OpenAPI document: 0.5.1-dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import graphsense
from graphsense.model.block import Block
globals()['Block'] = Block
from graphsense.model.blocks import Blocks


class TestBlocks(unittest.TestCase):
    """Blocks unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBlocks(self):
        """Test Blocks"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Blocks()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
