"""
    GraphSense API

    GraphSense API  # noqa: E501

    The version of the OpenAPI document: 1.0.0-alpha
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import graphsense
from graphsense.model.neighbor_address import NeighborAddress
globals()['NeighborAddress'] = NeighborAddress
from graphsense.model.neighbor_addresses import NeighborAddresses


class TestNeighborAddresses(unittest.TestCase):
    """NeighborAddresses unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNeighborAddresses(self):
        """Test NeighborAddresses"""
        # FIXME: construct object with mandatory attributes with example values
        # model = NeighborAddresses()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
