"""
    GraphSense API

    GraphSense API provides programmatic access to various ledgers' addresses, entities, blocks, transactions and tags for automated and highly efficient forensics tasks.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: contact@ikna.io
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import graphsense
from graphsense.model.address_tx import AddressTx
globals()['AddressTx'] = AddressTx
from graphsense.model.address_txs import AddressTxs


class TestAddressTxs(unittest.TestCase):
    """AddressTxs unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAddressTxs(self):
        """Test AddressTxs"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AddressTxs()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
