"""
    GraphSense API

    GraphSense API  # noqa: E501

    The version of the OpenAPI document: 0.5
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import graphsense
from graphsense.model.tx_account import TxAccount
globals()['TxAccount'] = TxAccount
from graphsense.model.txs_account import TxsAccount


class TestTxsAccount(unittest.TestCase):
    """TxsAccount unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTxsAccount(self):
        """Test TxsAccount"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TxsAccount()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
