"""
    GraphSense API

    GraphSense API  # noqa: E501

    The version of the OpenAPI document: 0.5
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import graphsense
from graphsense.model.operation import Operation


class TestOperation(unittest.TestCase):
    """Operation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOperation(self):
        """Test Operation"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Operation()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
