"""
    GraphSense API

    GraphSense API  # noqa: E501

    The version of the OpenAPI document: 0.4.5
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import graphsense
from graphsense.model.stats_ledger_version import StatsLedgerVersion
globals()['StatsLedgerVersion'] = StatsLedgerVersion
from graphsense.model.stats_ledger import StatsLedger


class TestStatsLedger(unittest.TestCase):
    """StatsLedger unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStatsLedger(self):
        """Test StatsLedger"""
        # FIXME: construct object with mandatory attributes with example values
        # model = StatsLedger()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
