"""
    GraphSense API

    GraphSense API  # noqa: E501

    The version of the OpenAPI document: 1.0.0-alpha
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import graphsense
from graphsense.model.address_tag_all_of import AddressTagAllOf


class TestAddressTagAllOf(unittest.TestCase):
    """AddressTagAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAddressTagAllOf(self):
        """Test AddressTagAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AddressTagAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
