"""
    GraphSense API

    GraphSense API provides programmatic access to various ledgers' addresses, entities, blocks, transactions and tags for automated and highly efficient forensics tasks.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: contact@ikna.io
    Generated by: https://openapi-generator.tech
"""


import unittest

import graphsense
from graphsense.api.blocks_api import BlocksApi  # noqa: E501


class TestBlocksApi(unittest.TestCase):
    """BlocksApi unit test stubs"""

    def setUp(self):
        self.api = BlocksApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_block(self):
        """Test case for get_block

        Get a block by its height  # noqa: E501
        """
        pass

    def test_list_block_txs(self):
        """Test case for list_block_txs

        Get block transactions  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
