"""
    GraphSense API

    GraphSense API  # noqa: E501

    The version of the OpenAPI document: 0.4.5
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import graphsense
from graphsense.model.block_eth import BlockEth
globals()['BlockEth'] = BlockEth
from graphsense.model.blocks_eth import BlocksEth


class TestBlocksEth(unittest.TestCase):
    """BlocksEth unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBlocksEth(self):
        """Test BlocksEth"""
        # FIXME: construct object with mandatory attributes with example values
        # model = BlocksEth()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
