"""
    GraphSense API

    GraphSense API provides programmatic access to various ledgers' addresses, entities, blocks, transactions and tags for automated and highly efficient forensics tasks.  # noqa: E501

    The version of the OpenAPI document: 1.7.0
    Contact: contact@ikna.io
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import graphsense
from graphsense.model.label_summary import LabelSummary
from graphsense.model.tag_cloud_entry import TagCloudEntry
globals()['LabelSummary'] = LabelSummary
globals()['TagCloudEntry'] = TagCloudEntry
from graphsense.model.tag_summary import TagSummary


class TestTagSummary(unittest.TestCase):
    """TagSummary unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTagSummary(self):
        """Test TagSummary"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TagSummary()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
