"""
    GraphSense API

    GraphSense API  # noqa: E501

    The version of the OpenAPI document: 0.4.5
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import graphsense
from graphsense.model.entity import Entity
from graphsense.model.entity_with_tags_all_of import EntityWithTagsAllOf
from graphsense.model.tag import Tag
from graphsense.model.tx_summary import TxSummary
from graphsense.model.values import Values
globals()['Entity'] = Entity
globals()['EntityWithTagsAllOf'] = EntityWithTagsAllOf
globals()['Tag'] = Tag
globals()['TxSummary'] = TxSummary
globals()['Values'] = Values
from graphsense.model.entity_with_tags import EntityWithTags


class TestEntityWithTags(unittest.TestCase):
    """EntityWithTags unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEntityWithTags(self):
        """Test EntityWithTags"""
        # FIXME: construct object with mandatory attributes with example values
        # model = EntityWithTags()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
