"""
    GraphSense API

    GraphSense API  # noqa: E501

    The version of the OpenAPI document: 0.4.5
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import graphsense
from graphsense.model.entity_tag import EntityTag
globals()['EntityTag'] = EntityTag
from graphsense.model.tags_by_entity import TagsByEntity


class TestTagsByEntity(unittest.TestCase):
    """TagsByEntity unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTagsByEntity(self):
        """Test TagsByEntity"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TagsByEntity()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
