"""
    GraphSense API

    GraphSense API provides programmatic access to various ledgers' addresses, entities, blocks, transactions and tags for automated and highly efficient forensics tasks.  # noqa: E501

    The version of the OpenAPI document: 1.2.0
    Contact: contact@ikna.io
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import graphsense
from graphsense.model.neighbor_address import NeighborAddress
globals()['NeighborAddress'] = NeighborAddress
from graphsense.model.neighbor_addresses import NeighborAddresses


class TestNeighborAddresses(unittest.TestCase):
    """NeighborAddresses unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNeighborAddresses(self):
        """Test NeighborAddresses"""
        # FIXME: construct object with mandatory attributes with example values
        # model = NeighborAddresses()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
