"""
    GraphSense API

    GraphSense API  # noqa: E501

    The version of the OpenAPI document: 0.4.5
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import graphsense
from graphsense.model.height import Height
from graphsense.model.tx import Tx
from graphsense.model.tx_eth import TxEth
from graphsense.model.tx_values import TxValues
from graphsense.model.values import Values
globals()['Height'] = Height
globals()['Tx'] = Tx
globals()['TxEth'] = TxEth
globals()['TxValues'] = TxValues
globals()['Values'] = Values
from graphsense.model.tx_union import TxUnion


class TestTxUnion(unittest.TestCase):
    """TxUnion unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTxUnion(self):
        """Test TxUnion"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TxUnion()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
