"""
    GraphSense API

    GraphSense API  # noqa: E501

    The version of the OpenAPI document: 0.5.2-dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import graphsense
from graphsense.model.only_entity_ids import OnlyEntityIds


class TestOnlyEntityIds(unittest.TestCase):
    """OnlyEntityIds unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOnlyEntityIds(self):
        """Test OnlyEntityIds"""
        # FIXME: construct object with mandatory attributes with example values
        # model = OnlyEntityIds()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
