"""
    GraphSense API

    GraphSense API  # noqa: E501

    The version of the OpenAPI document: 0.5.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import graphsense
from graphsense.model.neighbor import Neighbor
globals()['Neighbor'] = Neighbor
from graphsense.model.neighbors import Neighbors


class TestNeighbors(unittest.TestCase):
    """Neighbors unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNeighbors(self):
        """Test Neighbors"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Neighbors()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
