"""
    GraphSense API

    GraphSense API  # noqa: E501

    The version of the OpenAPI document: 0.5.1-dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import graphsense
from graphsense.model.stats_tool import StatsTool


class TestStatsTool(unittest.TestCase):
    """StatsTool unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStatsTool(self):
        """Test StatsTool"""
        # FIXME: construct object with mandatory attributes with example values
        # model = StatsTool()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
