"""
    GraphSense API

    GraphSense API  # noqa: E501

    The version of the OpenAPI document: 0.4.5
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import graphsense
from graphsense.model.tag import Tag
globals()['Tag'] = Tag
from graphsense.model.address_with_tags_all_of import AddressWithTagsAllOf


class TestAddressWithTagsAllOf(unittest.TestCase):
    """AddressWithTagsAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAddressWithTagsAllOf(self):
        """Test AddressWithTagsAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AddressWithTagsAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
