"""
    GraphSense API

    GraphSense API  # noqa: E501

    The version of the OpenAPI document: 0.5.2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import graphsense
from graphsense.model.entity_tag import EntityTag
globals()['EntityTag'] = EntityTag
from graphsense.model.entity_tags import EntityTags


class TestEntityTags(unittest.TestCase):
    """EntityTags unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEntityTags(self):
        """Test EntityTags"""
        # FIXME: construct object with mandatory attributes with example values
        # model = EntityTags()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
