"""
    GraphSense API

    GraphSense API  # noqa: E501

    The version of the OpenAPI document: 0.4.5
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import graphsense
from graphsense.model.tag import Tag
globals()['Tag'] = Tag
from graphsense.model.entity_with_tags_all_of import EntityWithTagsAllOf


class TestEntityWithTagsAllOf(unittest.TestCase):
    """EntityWithTagsAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEntityWithTagsAllOf(self):
        """Test EntityWithTagsAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = EntityWithTagsAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
