# coding: utf-8

"""
    GraphSense API

    GraphSense API  # noqa: E501

    The version of the OpenAPI document: 0.4.4
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import graphsense
from graphsense.api.entities_api import EntitiesApi  # noqa: E501
from graphsense.rest import ApiException


class TestEntitiesApi(unittest.TestCase):
    """EntitiesApi unit test stubs"""

    def setUp(self):
        self.api = graphsense.api.entities_api.EntitiesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_entity_with_tags(self):
        """Test case for get_entity_with_tags

        Get an entity with tags  # noqa: E501
        """
        pass

    def test_list_entity_addresses(self):
        """Test case for list_entity_addresses

        Get an entity's addresses  # noqa: E501
        """
        pass

    def test_list_entity_neighbors(self):
        """Test case for list_entity_neighbors

        Get an entity's neighbors in the entity graph  # noqa: E501
        """
        pass

    def test_list_entity_neighbors_csv(self):
        """Test case for list_entity_neighbors_csv

        Get an entity's neighbors in the entity graph as CSV  # noqa: E501
        """
        pass

    def test_list_entity_tags(self):
        """Test case for list_entity_tags

        Get attribution tags for a given entity  # noqa: E501
        """
        pass

    def test_list_entity_tags_csv(self):
        """Test case for list_entity_tags_csv

        Get attribution tags for a given entity as CSV  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
