"""
    GraphSense API

    GraphSense API provides programmatic access to various ledgers' addresses, entities, blocks, transactions and tags for automated and highly efficient forensics tasks.  # noqa: E501

    The version of the OpenAPI document: 1.3.0
    Contact: contact@ikna.io
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import graphsense
from graphsense.model.token_config import TokenConfig
globals()['TokenConfig'] = TokenConfig
from graphsense.model.token_configs import TokenConfigs


class TestTokenConfigs(unittest.TestCase):
    """TokenConfigs unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTokenConfigs(self):
        """Test TokenConfigs"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TokenConfigs()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
