"""
    GraphSense API

    GraphSense API provides programmatic access to various ledgers' addresses, entities, blocks, transactions and tags for automated and highly efficient forensics tasks.  # noqa: E501

    The version of the OpenAPI document: 22.10
    Contact: contact@ikna.io
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import graphsense
from graphsense.model.currency_stats import CurrencyStats
globals()['CurrencyStats'] = CurrencyStats
from graphsense.model.stats import Stats


class TestStats(unittest.TestCase):
    """Stats unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStats(self):
        """Test Stats"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Stats()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
