"""
    GraphSense API

    GraphSense API  # noqa: E501

    The version of the OpenAPI document: 0.4.5
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import graphsense
from graphsense.model.tx import Tx
globals()['Tx'] = Tx
from graphsense.model.txs import Txs


class TestTxs(unittest.TestCase):
    """Txs unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTxs(self):
        """Test Txs"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Txs()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
