# coding: utf-8

"""
    GraphSense API

    GraphSense API  # noqa: E501

    The version of the OpenAPI document: 0.4.4
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import graphsense
from graphsense.models.block_tx_summary import BlockTxSummary  # noqa: E501
from graphsense.rest import ApiException

class TestBlockTxSummary(unittest.TestCase):
    """BlockTxSummary unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test BlockTxSummary
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = graphsense.models.block_tx_summary.BlockTxSummary()  # noqa: E501
        if include_optional :
            return BlockTxSummary(
                no_inputs = 56, 
                no_outputs = 56, 
                total_input = graphsense.models.values.values(
                    eur = 56, 
                    usd = 56, 
                    value = 56, ), 
                total_output = graphsense.models.values.values(
                    eur = 56, 
                    usd = 56, 
                    value = 56, ), 
                tx_hash = '0'
            )
        else :
            return BlockTxSummary(
        )

    def testBlockTxSummary(self):
        """Test BlockTxSummary"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
