"""
    GraphSense API

    GraphSense API  # noqa: E501

    The version of the OpenAPI document: 0.5
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import graphsense
from graphsense.model.get_tx_io import GetTxIo
from graphsense.model.io import Io
globals()['GetTxIo'] = GetTxIo
globals()['Io'] = Io
from graphsense.model.batch_operation import BatchOperation


class TestBatchOperation(unittest.TestCase):
    """BatchOperation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBatchOperation(self):
        """Test BatchOperation"""
        # FIXME: construct object with mandatory attributes with example values
        # model = BatchOperation()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
