# coding: utf-8

"""
    GraphSense API

    GraphSense API  # noqa: E501

    The version of the OpenAPI document: 0.4.4
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import graphsense
from graphsense.models.blocks import Blocks  # noqa: E501
from graphsense.rest import ApiException

class TestBlocks(unittest.TestCase):
    """Blocks unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test Blocks
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = graphsense.models.blocks.Blocks()  # noqa: E501
        if include_optional :
            return Blocks(
                blocks = [
                    graphsense.models.block.block(
                        block_hash = '0', 
                        height = 1, 
                        no_txs = 56, 
                        timestamp = 56, )
                    ], 
                next_page = '0'
            )
        else :
            return Blocks(
        )

    def testBlocks(self):
        """Test Blocks"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
