"""
    GraphSense API

    GraphSense API  # noqa: E501

    The version of the OpenAPI document: 0.5
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import graphsense
from graphsense.model.get_tx_parameters import GetTxParameters
globals()['GetTxParameters'] = GetTxParameters
from graphsense.model.get_tx import GetTx


class TestGetTx(unittest.TestCase):
    """GetTx unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetTx(self):
        """Test GetTx"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetTx()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
