"""
    GraphSense API

    GraphSense API  # noqa: E501

    The version of the OpenAPI document: 0.5.1-dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import graphsense
from graphsense.model.entity_tag_all_of import EntityTagAllOf
from graphsense.model.tag import Tag
globals()['EntityTagAllOf'] = EntityTagAllOf
globals()['Tag'] = Tag
from graphsense.model.entity_tag import EntityTag


class TestEntityTag(unittest.TestCase):
    """EntityTag unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEntityTag(self):
        """Test EntityTag"""
        # FIXME: construct object with mandatory attributes with example values
        # model = EntityTag()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
