"""
    GraphSense API

    GraphSense API  # noqa: E501

    The version of the OpenAPI document: 0.5.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import graphsense
from graphsense.model.height import Height
globals()['Height'] = Height
from graphsense.model.tx_summary import TxSummary


class TestTxSummary(unittest.TestCase):
    """TxSummary unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTxSummary(self):
        """Test TxSummary"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TxSummary()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
