"""
    GraphSense API

    GraphSense API  # noqa: E501

    The version of the OpenAPI document: 0.5.1-dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import graphsense
from graphsense.model.currency_stats import CurrencyStats


class TestCurrencyStats(unittest.TestCase):
    """CurrencyStats unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCurrencyStats(self):
        """Test CurrencyStats"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CurrencyStats()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
