"""
    GraphSense API

    GraphSense API provides programmatic access to various ledgers' addresses, entities, blocks, transactions and tags for automated and highly efficient forensics tasks.  # noqa: E501

    The version of the OpenAPI document: 1.0.1
    Contact: contact@ikna.io
    Generated by: https://openapi-generator.tech
"""


import unittest

import graphsense
from graphsense.api.entities_api import EntitiesApi  # noqa: E501


class TestEntitiesApi(unittest.TestCase):
    """EntitiesApi unit test stubs"""

    def setUp(self):
        self.api = EntitiesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_entity(self):
        """Test case for get_entity

        Get an entity, optionally with tags  # noqa: E501
        """
        pass

    def test_list_address_tags_by_entity(self):
        """Test case for list_address_tags_by_entity

        Get address tags for a given entity  # noqa: E501
        """
        pass

    def test_list_entity_addresses(self):
        """Test case for list_entity_addresses

        Get an entity's addresses  # noqa: E501
        """
        pass

    def test_list_entity_links(self):
        """Test case for list_entity_links

        Get transactions between two entities  # noqa: E501
        """
        pass

    def test_list_entity_neighbors(self):
        """Test case for list_entity_neighbors

        Get an entity's neighbors in the entity graph  # noqa: E501
        """
        pass

    def test_list_entity_txs(self):
        """Test case for list_entity_txs

        Get all transactions an entity has been involved in  # noqa: E501
        """
        pass

    def test_search_entity_neighbors(self):
        """Test case for search_entity_neighbors

        Search deeply for matching neighbors  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
