"""
    GraphSense API

    GraphSense API  # noqa: E501

    The version of the OpenAPI document: 0.4.5
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import graphsense
from graphsense.model.entity import Entity
globals()['Entity'] = Entity
from graphsense.model.entities import Entities


class TestEntities(unittest.TestCase):
    """Entities unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEntities(self):
        """Test Entities"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Entities()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
