"""
    GraphSense API

    GraphSense API provides programmatic access to various ledgers' addresses, entities, blocks, transactions and tags for automated and highly efficient forensics tasks.  # noqa: E501

    The version of the OpenAPI document: 1.4.0
    Contact: contact@ikna.io
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import graphsense
from graphsense.model.address_tag import AddressTag
globals()['AddressTag'] = AddressTag
from graphsense.model.address_tags import AddressTags


class TestAddressTags(unittest.TestCase):
    """AddressTags unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAddressTags(self):
        """Test AddressTags"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AddressTags()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
