"""
    GraphSense API

    GraphSense API  # noqa: E501

    The version of the OpenAPI document: 0.5.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import graphsense
from graphsense.model.concept import Concept


class TestConcept(unittest.TestCase):
    """Concept unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testConcept(self):
        """Test Concept"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Concept()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
