"""
    GraphSense API

    GraphSense API  # noqa: E501

    The version of the OpenAPI document: 0.5
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import graphsense
from graphsense.model.get_tx_io_response import GetTxIoResponse
from graphsense.model.get_tx_io_result import GetTxIoResult
globals()['GetTxIoResponse'] = GetTxIoResponse
globals()['GetTxIoResult'] = GetTxIoResult
from graphsense.model.batch_response import BatchResponse


class TestBatchResponse(unittest.TestCase):
    """BatchResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBatchResponse(self):
        """Test BatchResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = BatchResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
