"""
    GraphSense API

    GraphSense API  # noqa: E501

    The version of the OpenAPI document: 0.5.2-dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import graphsense
from graphsense.model.height import Height
from graphsense.model.values import Values
globals()['Height'] = Height
globals()['Values'] = Values
from graphsense.model.tx_account import TxAccount


class TestTxAccount(unittest.TestCase):
    """TxAccount unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTxAccount(self):
        """Test TxAccount"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TxAccount()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
