# coding: utf-8

"""
    GraphSense API

    GraphSense API  # noqa: E501

    The version of the OpenAPI document: 0.4.4
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import graphsense
from graphsense.models.tx_value import TxValue  # noqa: E501
from graphsense.rest import ApiException

class TestTxValue(unittest.TestCase):
    """TxValue unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test TxValue
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = graphsense.models.tx_value.TxValue()  # noqa: E501
        if include_optional :
            return TxValue(
                address = [
                    '0'
                    ], 
                value = graphsense.models.values.values(
                    eur = 56, 
                    usd = 56, )
            )
        else :
            return TxValue(
                address = [
                    '0'
                    ],
                value = graphsense.models.values.values(
                    eur = 56, 
                    usd = 56, ),
        )

    def testTxValue(self):
        """Test TxValue"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
