"""
    GraphSense API

    GraphSense API  # noqa: E501

    The version of the OpenAPI document: 0.5
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import graphsense
from graphsense.model.list_entity_addresses_parameters import ListEntityAddressesParameters
globals()['ListEntityAddressesParameters'] = ListEntityAddressesParameters
from graphsense.model.list_entity_addresses import ListEntityAddresses


class TestListEntityAddresses(unittest.TestCase):
    """ListEntityAddresses unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testListEntityAddresses(self):
        """Test ListEntityAddresses"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ListEntityAddresses()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
