"""
    GraphSense API

    GraphSense API provides programmatic access to various ledgers' addresses, entities, blocks, transactions and tags for automated and highly efficient forensics tasks.  # noqa: E501

    The version of the OpenAPI document: 1.7.0
    Contact: contact@ikna.io
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import graphsense
from graphsense.model.label_summary import LabelSummary


class TestLabelSummary(unittest.TestCase):
    """LabelSummary unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLabelSummary(self):
        """Test LabelSummary"""
        # FIXME: construct object with mandatory attributes with example values
        # model = LabelSummary()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
