"""
    GraphSense API

    GraphSense API provides programmatic access to various ledgers' addresses, entities, blocks, transactions and tags for automated and highly efficient forensics tasks.  # noqa: E501

    The version of the OpenAPI document: 1.0.1
    Contact: contact@ikna.io
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import graphsense
from graphsense.model.tx_value import TxValue
globals()['TxValue'] = TxValue
from graphsense.model.tx_values import TxValues


class TestTxValues(unittest.TestCase):
    """TxValues unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTxValues(self):
        """Test TxValues"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TxValues()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
