"""
    GraphSense API

    GraphSense API provides programmatic access to various ledgers' addresses, entities, blocks, transactions and tags for automated and highly efficient forensics tasks.  # noqa: E501

    The version of the OpenAPI document: 1.1.1
    Contact: contact@ikna.io
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import graphsense
from graphsense.model.link import Link
globals()['Link'] = Link
from graphsense.model.links import Links


class TestLinks(unittest.TestCase):
    """Links unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLinks(self):
        """Test Links"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Links()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
