"""
    GraphSense API

    GraphSense API  # noqa: E501

    The version of the OpenAPI document: 0.5
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import graphsense
from graphsense.model.stats_ledger_version import StatsLedgerVersion


class TestStatsLedgerVersion(unittest.TestCase):
    """StatsLedgerVersion unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStatsLedgerVersion(self):
        """Test StatsLedgerVersion"""
        # FIXME: construct object with mandatory attributes with example values
        # model = StatsLedgerVersion()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
