"""
    GraphSense API

    GraphSense API  # noqa: E501

    The version of the OpenAPI document: 0.5
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import graphsense
from graphsense.model.get_tx_parameters import GetTxParameters


class TestGetTxParameters(unittest.TestCase):
    """GetTxParameters unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetTxParameters(self):
        """Test GetTxParameters"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetTxParameters()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
