"""
    GraphSense API

    GraphSense API  # noqa: E501

    The version of the OpenAPI document: 0.4.5
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import graphsense
from graphsense.model.tx_eth import TxEth
globals()['TxEth'] = TxEth
from graphsense.model.txs_eth import TxsEth


class TestTxsEth(unittest.TestCase):
    """TxsEth unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTxsEth(self):
        """Test TxsEth"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TxsEth()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
