"""
    GraphSense API

    GraphSense API  # noqa: E501

    The version of the OpenAPI document: 0.5
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import graphsense
from graphsense.model.rate import Rate
globals()['Rate'] = Rate
from graphsense.model.values import Values


class TestValues(unittest.TestCase):
    """Values unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testValues(self):
        """Test Values"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Values()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
