"""
    GraphSense API

    GraphSense API provides programmatic access to various ledgers' addresses, entities, blocks, transactions and tags for automated and highly efficient forensics tasks.  # noqa: E501

    The version of the OpenAPI document: 1.8.0
    Contact: contact@ikna.io
    Generated by: https://openapi-generator.tech
"""


from setuptools import setup, find_packages  # noqa: H301

NAME = "graphsense-python"
VERSION = "1.8.0"
# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools

project_urls = {
  'Source': 'https://github.com/graphsense/graphsense-python',
  'Changelog': 'https://github.com/graphsense/blob/master/CHANGELOG.md',
  'Tracker': 'https://github.com/graphsense/graphsense-python/issues',
}

REQUIRES = [
  "urllib3 >= 1.25.3",
  "python-dateutil",
]

with open("README.md", 'r') as f:
    long_description = f.read()

setup(
    name=NAME,
    version=VERSION,
    description="GraphSense API",
    author="Iknaio Cryptoasset Analytics GmbH",
    author_email="contact@ikna.io",
    url="https://graphsense.github.io/",
    project_urls=project_urls,
    keywords=["OpenAPI", "OpenAPI-Generator", "GraphSense API"],
    python_requires=">=3.6",
    install_requires=REQUIRES,
    packages=find_packages(exclude=["test", "tests"]),
    include_package_data=True,
    long_description=long_description,
    long_description_content_type = "text/markdown; charset=UTF-8; variant=GFM"
)
