# coding: utf-8

"""
    GraphSense API

    GraphSense API  # noqa: E501

    The version of the OpenAPI document: 0.4.5
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from graphsense.configuration import Configuration


class BlockTxs(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'height': 'int',
        'txs': 'list[BlockTxSummary]'
    }

    attribute_map = {
        'height': 'height',
        'txs': 'txs'
    }

    def __init__(self, height=None, txs=None, local_vars_configuration=None):  # noqa: E501
        """BlockTxs - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._height = None
        self._txs = None
        self.discriminator = None

        if height is not None:
            self.height = height
        if txs is not None:
            self.txs = txs

    @property
    def height(self):
        """Gets the height of this BlockTxs.  # noqa: E501

        Height  # noqa: E501

        :return: The height of this BlockTxs.  # noqa: E501
        :rtype: int
        """
        return self._height

    @height.setter
    def height(self, height):
        """Sets the height of this BlockTxs.

        Height  # noqa: E501

        :param height: The height of this BlockTxs.  # noqa: E501
        :type height: int
        """
        if (self.local_vars_configuration.client_side_validation and
                height is not None and height < 1):  # noqa: E501
            raise ValueError("Invalid value for `height`, must be a value greater than or equal to `1`")  # noqa: E501

        self._height = height

    @property
    def txs(self):
        """Gets the txs of this BlockTxs.  # noqa: E501


        :return: The txs of this BlockTxs.  # noqa: E501
        :rtype: list[BlockTxSummary]
        """
        return self._txs

    @txs.setter
    def txs(self, txs):
        """Sets the txs of this BlockTxs.


        :param txs: The txs of this BlockTxs.  # noqa: E501
        :type txs: list[BlockTxSummary]
        """

        self._txs = txs

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, BlockTxs):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, BlockTxs):
            return True

        return self.to_dict() != other.to_dict()
