# coding: utf-8

"""
    GraphSense API

    GraphSense API  # noqa: E501

    The version of the OpenAPI document: 0.4.4
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from graphsense.configuration import Configuration


class Concept(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'description': 'str',
        'id': 'str',
        'label': 'str',
        'taxonomy': 'str',
        'uri': 'str'
    }

    attribute_map = {
        'description': 'description',
        'id': 'id',
        'label': 'label',
        'taxonomy': 'taxonomy',
        'uri': 'uri'
    }

    def __init__(self, description=None, id=None, label=None, taxonomy=None, uri=None, local_vars_configuration=None):  # noqa: E501
        """Concept - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._description = None
        self._id = None
        self._label = None
        self._taxonomy = None
        self._uri = None
        self.discriminator = None

        self.description = description
        self.id = id
        self.label = label
        self.taxonomy = taxonomy
        self.uri = uri

    @property
    def description(self):
        """Gets the description of this Concept.  # noqa: E501

        Description  # noqa: E501

        :return: The description of this Concept.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this Concept.

        Description  # noqa: E501

        :param description: The description of this Concept.  # noqa: E501
        :type description: str
        """
        if self.local_vars_configuration.client_side_validation and description is None:  # noqa: E501
            raise ValueError("Invalid value for `description`, must not be `None`")  # noqa: E501

        self._description = description

    @property
    def id(self):
        """Gets the id of this Concept.  # noqa: E501

        ID  # noqa: E501

        :return: The id of this Concept.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Concept.

        ID  # noqa: E501

        :param id: The id of this Concept.  # noqa: E501
        :type id: str
        """
        if self.local_vars_configuration.client_side_validation and id is None:  # noqa: E501
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def label(self):
        """Gets the label of this Concept.  # noqa: E501

        Label  # noqa: E501

        :return: The label of this Concept.  # noqa: E501
        :rtype: str
        """
        return self._label

    @label.setter
    def label(self, label):
        """Sets the label of this Concept.

        Label  # noqa: E501

        :param label: The label of this Concept.  # noqa: E501
        :type label: str
        """
        if self.local_vars_configuration.client_side_validation and label is None:  # noqa: E501
            raise ValueError("Invalid value for `label`, must not be `None`")  # noqa: E501

        self._label = label

    @property
    def taxonomy(self):
        """Gets the taxonomy of this Concept.  # noqa: E501

        Taxonomy  # noqa: E501

        :return: The taxonomy of this Concept.  # noqa: E501
        :rtype: str
        """
        return self._taxonomy

    @taxonomy.setter
    def taxonomy(self, taxonomy):
        """Sets the taxonomy of this Concept.

        Taxonomy  # noqa: E501

        :param taxonomy: The taxonomy of this Concept.  # noqa: E501
        :type taxonomy: str
        """
        if self.local_vars_configuration.client_side_validation and taxonomy is None:  # noqa: E501
            raise ValueError("Invalid value for `taxonomy`, must not be `None`")  # noqa: E501

        self._taxonomy = taxonomy

    @property
    def uri(self):
        """Gets the uri of this Concept.  # noqa: E501

        URI  # noqa: E501

        :return: The uri of this Concept.  # noqa: E501
        :rtype: str
        """
        return self._uri

    @uri.setter
    def uri(self, uri):
        """Sets the uri of this Concept.

        URI  # noqa: E501

        :param uri: The uri of this Concept.  # noqa: E501
        :type uri: str
        """
        if self.local_vars_configuration.client_side_validation and uri is None:  # noqa: E501
            raise ValueError("Invalid value for `uri`, must not be `None`")  # noqa: E501

        self._uri = uri

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Concept):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, Concept):
            return True

        return self.to_dict() != other.to_dict()
