# coding: utf-8

"""
    GraphSense API

    GraphSense API  # noqa: E501

    The version of the OpenAPI document: 0.4.4
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from graphsense.configuration import Configuration


class StatsVersion(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'file': 'str',
        'hash': 'str',
        'nr': 'str',
        'timestamp': 'str'
    }

    attribute_map = {
        'file': 'file',
        'hash': 'hash',
        'nr': 'nr',
        'timestamp': 'timestamp'
    }

    def __init__(self, file=None, hash=None, nr=None, timestamp=None, local_vars_configuration=None):  # noqa: E501
        """StatsVersion - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._file = None
        self._hash = None
        self._nr = None
        self._timestamp = None
        self.discriminator = None

        if file is not None:
            self.file = file
        if hash is not None:
            self.hash = hash
        if nr is not None:
            self.nr = nr
        if timestamp is not None:
            self.timestamp = timestamp

    @property
    def file(self):
        """Gets the file of this StatsVersion.  # noqa: E501


        :return: The file of this StatsVersion.  # noqa: E501
        :rtype: str
        """
        return self._file

    @file.setter
    def file(self, file):
        """Sets the file of this StatsVersion.


        :param file: The file of this StatsVersion.  # noqa: E501
        :type file: str
        """

        self._file = file

    @property
    def hash(self):
        """Gets the hash of this StatsVersion.  # noqa: E501


        :return: The hash of this StatsVersion.  # noqa: E501
        :rtype: str
        """
        return self._hash

    @hash.setter
    def hash(self, hash):
        """Sets the hash of this StatsVersion.


        :param hash: The hash of this StatsVersion.  # noqa: E501
        :type hash: str
        """

        self._hash = hash

    @property
    def nr(self):
        """Gets the nr of this StatsVersion.  # noqa: E501


        :return: The nr of this StatsVersion.  # noqa: E501
        :rtype: str
        """
        return self._nr

    @nr.setter
    def nr(self, nr):
        """Sets the nr of this StatsVersion.


        :param nr: The nr of this StatsVersion.  # noqa: E501
        :type nr: str
        """

        self._nr = nr

    @property
    def timestamp(self):
        """Gets the timestamp of this StatsVersion.  # noqa: E501


        :return: The timestamp of this StatsVersion.  # noqa: E501
        :rtype: str
        """
        return self._timestamp

    @timestamp.setter
    def timestamp(self, timestamp):
        """Sets the timestamp of this StatsVersion.


        :param timestamp: The timestamp of this StatsVersion.  # noqa: E501
        :type timestamp: str
        """

        self._timestamp = timestamp

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, StatsVersion):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, StatsVersion):
            return True

        return self.to_dict() != other.to_dict()
