# coding: utf-8

"""
    GraphSense API

    GraphSense API  # noqa: E501

    The version of the OpenAPI document: 0.4.5
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from graphsense.configuration import Configuration


class Txs(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'next_page': 'str',
        'txs': 'list[Tx]'
    }

    attribute_map = {
        'next_page': 'next_page',
        'txs': 'txs'
    }

    def __init__(self, next_page=None, txs=None, local_vars_configuration=None):  # noqa: E501
        """Txs - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._next_page = None
        self._txs = None
        self.discriminator = None

        if next_page is not None:
            self.next_page = next_page
        if txs is not None:
            self.txs = txs

    @property
    def next_page(self):
        """Gets the next_page of this Txs.  # noqa: E501


        :return: The next_page of this Txs.  # noqa: E501
        :rtype: str
        """
        return self._next_page

    @next_page.setter
    def next_page(self, next_page):
        """Sets the next_page of this Txs.


        :param next_page: The next_page of this Txs.  # noqa: E501
        :type next_page: str
        """

        self._next_page = next_page

    @property
    def txs(self):
        """Gets the txs of this Txs.  # noqa: E501


        :return: The txs of this Txs.  # noqa: E501
        :rtype: list[Tx]
        """
        return self._txs

    @txs.setter
    def txs(self, txs):
        """Sets the txs of this Txs.


        :param txs: The txs of this Txs.  # noqa: E501
        :type txs: list[Tx]
        """

        self._txs = txs

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Txs):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, Txs):
            return True

        return self.to_dict() != other.to_dict()
